---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: prometheus-storage
reclaimPolicy: kubernetes.io/gce-pd
parameters:
  type: pd-standard
provisioner: kubernetes.io/gce-pd
allowVolumeExpansion: true
